logging:
  level:
    org.springframework.boot: DEBUG

greeting:
  message: default prod config,this

NIDA:
  authorization: usernamepassword
  services:
    passport_application:
      request_type: POST
      request_format: JSON
      response_format: JSON
      live_url: http://nida.com/some/live/nida/url/passport
      sandbox_url: http://nida.com/some/sandbox/nida/url/passport
      request_async: true

    passport_renewal:
      request_type: POST
      request_format: JSON
      response_format: JSON
      live_url: http://nida.com/some/live/nida/url/passport_renewal
      sandbox_url: http://nida.com/some/sandbox/nida/url/passport_renewal
      request_async: true    

RRA:
  request_type: POST
  request_format: JSON
  response_format: JSON
  authentication_token_expiry_secs: 0
  token_credentials: RRA123
  request_async: false
  
RSSB:
  request_type: POST
  request_format: XML
  response_format: XML
  authentication_token_expiry_secs: 0
  token_credentials: RSSB123
  request_async: false

RURA:
  request_type: POST
  request_format: XML
  response_format: XML
  authentication_token_expiry_secs: 0
  token_credentials: RURA123
  request_async: false
