logging:
  level:
    org.springframework.boot: DEBUG

greeting:
  message: default prod config,this

authorization: usernamepassword
auth_username: user
auth_password: pass
    
services:
    passport_application:
        request_type: POST
        request_format: JSON
        response_format: JSON
        ext_url: http://dgie.com/some/live/dgie/url/passport_application
        response_url: http://irembogov.rw/passport_application
        request_async: true
        queue: q_dgie_passport_application
        route: r_dgie_passport_application
        log: l_dgie_passport_application.file

    passport_renewal:
        request_type: POST
        request_format: JSON
        response_format: JSON
        ext_url: http://dgie.com/some/live/dgie/url/passport_renewal
        response_url: http://irembogov.rw/passport_renewal
        request_async: true 
        queue: q_dgie_passport_renewal
        route: r_dgie_passport_renewal
        log: l_dgie_passport_renewal.file   