logging:
  level:
    org.springframework.boot: DEBUG

greeting:
  message: default dev config,this

NIDA:
  request_type: POST
  request_format: XML
  response_format: XML
  authentication_token_expiry_secs: 0
  token_credentials: NIDA123
  request_async: true

RRA:
  request_type: POST
  request_format: XML
  response_format: XML
  authentication_token_expiry_secs: 0
  token_credentials: NIDA123
  request_async: false
